secretsprovider: awskms://alias/rag-pulumi?region=us-east-1
encryptedkey: AQICAHgpkF8raK9xv/ip2rAyvZVW3gPszeDX5uwRQb3Y/ds4LwFXyKzhDxy1c3ywenpcL4UpAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVeNdSzEDpA+0DYS6AgEQgDup+EIiHB+N0qEA0+UcvNWxAwxUlnG33N2VWmwNtOudDmsQinOYy5+5JGvYiV2+Yjz9odK9FRvloXjnKQ==
config:
  aws:region: us-east-1
  aws:profile: walker-rag-app
  rag:honeycombApiKey:
    secure: v1:xhEbVcOdFHmbhcNY:myJFEYq6xAPQbhHo2wnhwklbVkSObrC+TsWuyT/JK1Nu2MIsDv4=
