"""Persistence models for the canonical corpus.

Identifiers are UUIDs generated by the application, so a record keeps the same identity
when the graph projection is rebuilt from these tables.
"""

import uuid
from datetime import date, datetime, timedelta

from sqlalchemy import (
    CheckConstraint,
    Computed,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Interval,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY, TSVECTOR, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from storage.postgres import Base


def _uuid_column() -> Mapped[uuid.UUID]:
    return mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)


class IngestionRun(Base):
    """One attempt to ingest from a source. Failed runs are kept, not deleted."""

    __tablename__ = "ingestion_run"

    id: Mapped[uuid.UUID] = _uuid_column()
    source: Mapped[str] = mapped_column(String(64))
    status: Mapped[str] = mapped_column(String(16))
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    error: Mapped[str | None] = mapped_column(Text)

    __table_args__ = (
        CheckConstraint(
            "status in ('running', 'succeeded', 'failed')", name="ingestion_run_status_valid"
        ),
    )


class Speaker(Base):
    """A person who speaks in at least one episode. Shared across episodes by name."""

    __tablename__ = "speaker"

    id: Mapped[uuid.UUID] = _uuid_column()
    name: Mapped[str] = mapped_column(String(200), unique=True)
    # The run that first saw this speaker.
    ingestion_run_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("ingestion_run.id"))


class Episode(Base):
    __tablename__ = "episode"

    id: Mapped[uuid.UUID] = _uuid_column()
    # The publisher's own identifier, which makes re-ingestion recognisable.
    source_id: Mapped[str] = mapped_column(String(200), unique=True)
    title: Mapped[str] = mapped_column(Text)
    url: Mapped[str] = mapped_column(Text)
    published_at: Mapped[date] = mapped_column(Date)
    ingestion_run_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("ingestion_run.id"))

    segments: Mapped[list["TranscriptSegment"]] = relationship(
        back_populates="episode", cascade="all, delete-orphan"
    )


class EpisodeSpeaker(Base):
    """Which speakers appear in which episode."""

    __tablename__ = "episode_speaker"

    episode_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("episode.id", ondelete="CASCADE"), primary_key=True
    )
    speaker_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("speaker.id", ondelete="CASCADE"), primary_key=True
    )


class TranscriptSegment(Base):
    """One speaker turn. Position is the turn's place in the episode, counted from zero."""

    __tablename__ = "transcript_segment"

    id: Mapped[uuid.UUID] = _uuid_column()
    episode_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("episode.id", ondelete="CASCADE"), index=True
    )
    speaker_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("speaker.id"))
    position: Mapped[int] = mapped_column()
    text: Mapped[str] = mapped_column(Text)
    # Null for episodes whose transcript markup carries no inline timestamps.
    start: Mapped[timedelta | None] = mapped_column(Interval)
    ingestion_run_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("ingestion_run.id"))

    episode: Mapped[Episode] = relationship(back_populates="segments")

    __table_args__ = (
        UniqueConstraint("episode_id", "position", name="transcript_segment_position_unique"),
        CheckConstraint("position >= 0", name="transcript_segment_position_non_negative"),
    )


class Chunk(Base):
    """A retrieval unit covering a contiguous range of one episode's turns."""

    __tablename__ = "chunk"

    id: Mapped[uuid.UUID] = _uuid_column()
    episode_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("episode.id", ondelete="CASCADE"), index=True
    )
    ordinal: Mapped[int] = mapped_column(Integer)
    first_position: Mapped[int] = mapped_column(Integer)
    last_position: Mapped[int] = mapped_column(Integer)
    # Denormalised from the turns this chunk covers, so filtering needs no join.
    speakers: Mapped[list[str]] = mapped_column(ARRAY(String(200)))
    text: Mapped[str] = mapped_column(Text)
    start: Mapped[timedelta | None] = mapped_column(Interval)
    # Which chunking rules produced this row, so a change of rules is detectable.
    chunker_version: Mapped[str] = mapped_column(String(16))
    # Maintained by Postgres, so the text and its index cannot drift apart.
    search: Mapped[str] = mapped_column(
        TSVECTOR, Computed("to_tsvector('english', text)", persisted=True)
    )

    __table_args__ = (
        UniqueConstraint("episode_id", "ordinal", name="chunk_ordinal_unique"),
        CheckConstraint("first_position <= last_position", name="chunk_positions_ordered"),
        CheckConstraint("first_position >= 0", name="chunk_first_position_non_negative"),
        Index("ix_chunk_search", "search", postgresql_using="gin"),
        Index("ix_chunk_speakers", "speakers", postgresql_using="gin"),
    )
